import os
env = SpecialEnvironment()

Import('*')

print("Parsing", self.name, ":", self.platform, self.arch, self.bits)

lib = env.ImportLibrary(self, 'common')

if 'x86_64' in self.arch:
    env.Append(LINKFLAGS='-rdynamic')

p = env.Program('program', SpecialGlob(self, '*.c'), LIBS=[lib])

exported = env.Install(self.export_dir(), p)
Default(exported)
env.Alias(os.path.join('build', self.path(), self.name), exported)
env.Alias(os.path.join('build', self.path()), exported)
env.Alias(self.path(), exported)
Return('exported')