import os
env = SpecialEnvironment()

Import('*')

print("Parsing", self.name, ":", self.platform, self.arch, self.bits)

if 'x86_64' in self.arch:
    env.Append(LINKFLAGS='-rdynamic')

p = env.Program('program', SpecialGlob(self, '*.c'), LIBS=['common'], CPPPATH="$COMMON_INCLUDES")

exported = env.Install("$EXPORT_DIR", p)
Default(exported)
env.Alias(os.path.join('build', self.path(), self.name), exported)
env.Alias(os.path.join('build', self.path()), exported)
env.Alias(self.path(), exported)
Return('exported')