env = Environment()

Import('self')

# put common in the parent build folder and not common build folder
env.Include(self.parent, 'common')

if 'arm' in self.arch:
	env.Append(CPPDEFINES={'FLAGVALUE': 666})
else:
	env.Append(CPPDEFINES={'FLAGVALUE': 1})

library = env.Library('common', SpecialGlob(self, '*.c'))

Return('library')