env = Environment()

Import('self')

# put common in the parent build folder and not common build folder
env.Include(self.parent, 'common')

if 'linux' in self.options['platform']:
	env.Append(CPPDEFINES={'FLAGVALUE': 666})
else:
	env.Append(CPPDEFINES={'FLAGVALUE': 1})

library = env.Library('common', Glob('*.c'))

Return('library')