# put common in the parent build folder and not common build folder
try:
	Import('self')
	Import('env')
except:
	env = SpecialEnvironment()
	env.Include(self, 'common')

if 'linux' in self.options['platform']:
	env.Append(CPPDEFINES={'FLAGVALUE': 666})
else:
	env.Append(CPPDEFINES={'FLAGVALUE': 1})

library = env.Library('common', SpecialGlob(self, '*.c'))

Return('library')