import os
env = SpecialEnvironment()

Import('self')
print("Parsing '%s' with options:\n\t%s" % (self.name, self.options))

# Includes('common', env)
lib = env.ImportLibrary(self, 'common')

if 'linux' in self.options["platform"]:
    env.Append(LINKFLAGS='-rdynamic')

p = env.Program('program', SpecialGlob(self, '*.c'), LIBS=[lib])

exported = env.Install(os.path.join('#/export', self.path()), p)
Default(exported)
env.Alias(os.path.join('#/build', self.path()), exported)
env.Alias(self.originalName, exported)
Return('exported')