import os
env = Environment()

Import('self')

print("Parsing '%s'" % self.name)

Includes('common', env)

p = env.Program('program', Glob('*.c'), libs=['common'])

i = env.Install(os.path.join(GetLaunchDir(), 'export'), p)
Default(i)
Return('p')