Import('self', 'env')

if 'arm' in self.arch:
    env.Append(CPPDEFINES={'FLAGVALUE': 666})
else:
    env.Append(CPPDEFINES={'FLAGVALUE': 1})

library = env.Library('common', SpecialGlob(self, '*.c'), CPPPATH=[Dir('includes')])
env['COMMON_INCLUDES'] = [Dir('includes/$TARGET_PLATFORM/$TARGET_ARCH/$TARGET_BITS'), Dir('includes/$TARGET_PLATFORM/$TARGET_ARCH'),
                          Dir('includes/$TARGET_PLATFORM'), Dir('includes')]
Return('library')
